### ISSUE TITLE
"the application did not respond"

### ISSUE THREAD

**Issue by imyourcousintd** [mgiovani/my-instants-discord-bot#11]
Allowed admin access on the discord. When I type /mi is opens a search. No matter what I type in, it shows the red error message "the application did not respond"

I'm looking to have myinstant audio clips play in the discord voice channels.

Help? Many thanks.

**Comment by imyourcousintd** [comment]
bump ^

Kindly :)

**Comment by imyourcousintd** [comment]
<img width="410" height="115" alt="Image" src="https://github.com/user-attachments/assets/472af35b-d509-462f-9a72-049c643d04d7" />

issue remains

**Comment by mgiovani** [comment]
Hi @imyourcousintd, thanks for reporting this and sorry for the delayed response.
I haven't had much time to maintain this project lately.

I've just opened a PR (#13) that should fix this issue.
If you're still using the bot, would you mind testing it later?

**Comment by imyourcousintd** [comment]
<img width="490" height="165" alt="Image" src="https://github.com/user-attachments/assets/477b1600-1b94-40e5-a6d3-11ba3f47c495" />

**Comment by imyourcousintd** [comment]
Bot is enabled on our server, of which I am an admin. Still not working :/

**Comment by imyourcousintd** [comment]
heres a few more commands I tried. I'm logged into the MyInstants on another tab. Search, and therefore play doesnt work 

<img width="530" height="966" alt="Image" src="https://github.com/user-attachments/assets/9eba311c-a909-49f4-a8cd-92d5c60077f7" />

_
